"""
List of different refinement combination strategies, with accompanying
error indicator refinement parameters.
"""

# Uniform angular refinemnt
h_uni_ang  = {'full_name'  : 'Uniform Angular h-Refinement',
              'short_name' : 'h-uni-ang',
              'ref_kind'   : 'ang',
              'ndofs'      : [8, 8, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 1}

p_uni_ang  = {'full_name'  : 'Uniform Angular p-Refinement',
              'short_name' : 'p-uni-ang',
              'ref_kind'   : 'ang',
              'ndofs'      : [8, 8, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 3}

hp_uni_ang = {'full_name'  : 'Uniform Angular hp-Refinement',
              'short_name' : 'hp-uni-ang',
              'ref_kind'   : 'ang',
              'ndofs'      : [8, 8, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 3}

# Uniform spatial refinement
h_uni_spt  = {'full_name'  : 'Uniform Spatial h-Refinement',
              'short_name' : 'h-uni-spt',
              'ref_kind'   : 'spt',
              'ndofs'      : [3, 3, 8],
              'nref_ang'   : 3,
              'nref_spt'   : 2}

p_uni_spt  = {'full_name'  : 'Uniform Spatial p-Refinement',
              'short_name' : 'p-uni-spt',
              'ref_kind'   : 'spt',
              'ndofs'      : [3, 3, 8],
              'nref_ang'   : 3,
              'nref_spt'   : 2}

hp_uni_spt = {'full_name'  : 'Uniform Spatial hp-Refinement',
              'short_name' : 'hp-uni-spt',
              'ref_kind'   : 'spt',
              'ndofs'      : [3, 3, 8],
              'nref_ang'   : 3,
              'nref_spt'   : 2}

# Uniform spatio-angular refinemnt
h_uni_all  = {'full_name'  : 'Uniform Spatio-Angular h-Refinement',
              'short_name' : 'h-uni-all',
              'ref_kind'   : 'all',
              'ndofs'      : [3, 3, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 2}

p_uni_all  = {'full_name'  : 'Uniform Spatio-Angular p-Refinement',
              'short_name' : 'p-uni-all',
              'ref_kind'   : 'all',
              'ndofs'      : [3, 3, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 2}

hp_uni_all = {'full_name'  : 'Uniform Spatio-Angular hp-Refinement',
              'short_name' : 'hp-uni-all',
              'ref_kind'   : 'all',
              'ndofs'      : [3, 3, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 2}

# Adaptive angular refinement
h_amr_ang  = {'full_name'  : 'Adaptive Angular h-Refinement',
              'short_name' : 'h-amr-ang',
              'ref_kind'   : 'ang',
              'ndofs'      : [8, 8, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 3,
              'kwargs_ang_nneg' : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'h',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : -0.01},
              'kwargs_ang_jmp'  : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'h',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : 0.9}
              }

p_amr_ang  = {'full_name'  : 'Adaptive Angular p-Refinement',
              'short_name' : 'p-amr-ang',
              'ref_kind'   : 'ang',
              'ndofs'      : [8, 8, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 3,
              'kwargs_ang_nneg' : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'p',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : -0.01},
              'kwargs_ang_jmp'  : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'p',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : 0.9}
              }

hp_amr_ang = {'full_name'  : 'Adaptive Angular hp-Refinement',
              'short_name' : 'hp-amr-ang',
              'ref_kind'   : 'ang',
              'ndofs'      : [8, 8, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 3,
              'kwargs_ang_nneg' : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'h',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : -0.01},
              'kwargs_ang_jmp'  : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'hp',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : 0.9}
              }

# Adaptive spatial refinement
h_amr_spt  = {'full_name'  : 'Adaptive Spatial h-Refinement',
              'short_name' : 'h-amr-spt',
              'ref_kind'   : 'spt',
              'ndofs'      : [3, 3, 8],
              'nref_ang'   : 3,
              'nref_spt'   : 2,
              'kwargs_spt_nneg' : {'ref_col'       : True,
                                   'col_ref_form'  : 'h',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : -0.01,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None},
              'kwargs_spt_jmp'  : {'ref_col'       : True,
                                   'col_ref_form'  : 'h',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : 0.9,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None}
              }

p_amr_spt  = {'full_name'  : 'Adaptive Spatial p-Refinement',
              'short_name' : 'p-amr-spt',
              'ref_kind'   : 'spt',
              'ndofs'      : [3, 3, 8],
              'nref_ang'   : 3,
              'nref_spt'   : 2,
              'kwargs_spt_nneg' : {'ref_col'       : True,
                                   'col_ref_form'  : 'p',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : -0.01,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None},
              'kwargs_spt_jmp'  : {'ref_col'       : True,
                                   'col_ref_form'  : 'p',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : 0.9,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None}
              }

hp_amr_spt = {'full_name'  : 'Adaptive Spatial hp-Refinement',
              'short_name' : 'hp-amr-spt',
              'ref_kind'   : 'spt',
              'ndofs'      : [3, 3, 8],
              'nref_ang'   : 3,
              'nref_spt'   : 2,
              'kwargs_spt_nneg' : {'ref_col'       : True,
                                   'col_ref_form'  : 'h',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : -0.01,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None},
              'kwargs_spt_jmp'  : {'ref_col'       : True,
                                   'col_ref_form'  : 'hp',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : 0.9,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None}
              }

# Adaptive spatio-angular refinement
h_amr_all  = {'full_name'  : 'Adaptive Spatio-Angular h-Refinement',
              'short_name' : 'h-amr-all',
              'ref_kind'   : 'all',
              'ndofs'      : [3, 3, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 2,
              'kwargs_ang_nneg' : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'h',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : -0.01},
              'kwargs_spt_nneg' : {'ref_col'       : True,
                                   'col_ref_form'  : 'h',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : -0.01,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None},
              'kwargs_ang_jmp'  : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'h',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : 0.9},
              'kwargs_spt_jmp'  : {'ref_col'       : True,
                                   'col_ref_form'  : 'h',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : 0.9,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None}
              }

p_amr_all  = {'full_name'  : 'Adaptive Spatio-Angular p-Refinement',
              'short_name' : 'p-amr-all',
              'ref_kind'   : 'all',
              'ndofs'      : [3, 3, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 2,
              'kwargs_ang_nneg' : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'p',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : -0.01},
              'kwargs_spt_nneg' : {'ref_col'       : True,
                                   'col_ref_form'  : 'p',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : -0.01,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None},
              'kwargs_ang_jmp'  : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'p',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : 0.9},
              'kwargs_spt_jmp'  : {'ref_col'       : True,
                                   'col_ref_form'  : 'p',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : 0.9,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None}
              }

hp_amr_all = {'full_name'  : 'Adaptive Spatio-Angular hp-Refinement',
              'short_name' : 'hp-amr-all',
              'ref_kind'   : 'all',
              'ndofs'      : [3, 3, 3],
              'nref_ang'   : 2,
              'nref_spt'   : 2,
              'kwargs_ang_nneg' : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'h',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : -0.01},
              'kwargs_spt_nneg' : {'ref_col'       : True,
                                   'col_ref_form'  : 'h',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : -0.01,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None},
              'kwargs_ang_jmp'  : {'ref_col'       : False,
                                   'col_ref_form'  : None,
                                   'col_ref_kind'  : None,
                                   'col_ref_tol'   : None,
                                   'ref_cell'      : True,
                                   'cell_ref_form' : 'hp',
                                   'cell_ref_kind' : 'ang',
                                   'cell_ref_tol'  : 0.9},
              'kwargs_spt_jmp'  : {'ref_col'       : True,
                                   'col_ref_form'  : 'hp',
                                   'col_ref_kind'  : 'spt',
                                   'col_ref_tol'   : 0.9,
                                   'ref_cell'      : False,
                                   'cell_ref_form' : None,
                                   'cell_ref_kind' : None,
                                   'cell_ref_tol'  : None}
              }
